name: Rust

on:
  push:
    tags:
      - 'v*' # Only create a release on version tags like v1.0.0
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target for Windows
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build Windows executable
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Rename executable for upload
        run: |
          mkdir -p dist
          cp target/x86_64-pc-windows-gnu/release/se_loader_linux.exe dist/se_loader_linux.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/se_loader_linux.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

