name: Rust Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install MinGW for Windows build
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Rename executable for upload
        run: |
          mkdir -p dist
          cp target/x86_64-pc-windows-gnu/release/se_loader_linux.exe dist/se_loader_linux.exe

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/se_loader_linux.exe
          asset_name: se_loader_windows.exe
          asset_content_type: application/executable
